"""all

Revision ID: edd7ac27e68e
Revises: ffd9d2858f2b
Create Date: 2024-01-23 10:32:40.520491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edd7ac27e68e'
down_revision = 'ffd9d2858f2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('all', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('all', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.drop_constraint('all_employee_username_fkey', 'all', type_='foreignkey')
    op.drop_constraint('all_user_username_fkey', 'all', type_='foreignkey')
    op.create_foreign_key(None, 'all', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'all', 'employees', ['employee_id'], ['id'])
    op.drop_column('all', 'user_username')
    op.drop_column('all', 'employee_username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('all', sa.Column('employee_username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('all', sa.Column('user_username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'all', type_='foreignkey')
    op.drop_constraint(None, 'all', type_='foreignkey')
    op.create_foreign_key('all_user_username_fkey', 'all', 'users', ['user_username'], ['username'])
    op.create_foreign_key('all_employee_username_fkey', 'all', 'employees', ['employee_username'], ['username'])
    op.drop_column('all', 'employee_id')
    op.drop_column('all', 'user_id')
    # ### end Alembic commands ###
