"""initial

Revision ID: ffd9d2858f2b
Revises: b19fd032079b
Create Date: 2024-01-23 10:17:56.802417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffd9d2858f2b'
down_revision = 'b19fd032079b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('all',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_username', sa.String(), nullable=True),
    sa.Column('employee_username', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_username'], ['employees.username'], ),
    sa.ForeignKeyConstraint(['user_username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_all_id'), 'all', ['id'], unique=False)
    op.add_column('employees', sa.Column('user_username', sa.String(), nullable=True))
    op.create_foreign_key(None, 'employees', 'users', ['user_username'], ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'user_username')
    op.drop_index(op.f('ix_all_id'), table_name='all')
    op.drop_table('all')
    # ### end Alembic commands ###
