version: '3'
services:
  postgres:
    image: postgres:latest
    volumes:
      - "pg_data:/var/lib/postgresql/data"
    ports:
      - "127.0.0.1:5434:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres





